/**
 * PR / project-closure renderer for `spear resolve`.
 *
 * Resolve is SPEAR's close-out phase. Its canonical deliverable is the closure
 * document — highlights, lowlights, what to test, warnings, next steps. Inside
 * a git repo it doubles as a PR description; outside one it stands alone as a
 * handoff doc.
 *
 * Source data:
 *   - SCOPE.md            → title (first non-blank line of "## Goal")
 *   - state.json          → rounds, lastAssess, blockers, completedAt, history
 *   - RESOLVE.md          → most-recent <spear-report> (COMPLETED, NEXT, BLOCKERS)
 *   - .spear/rounds/N/    → per-round assess.json + evidence.json
 *
 * Customization: a `.spear/pr-template.md` (or path passed via --template)
 * with handlebars-style `{{var}}` placeholders is rendered with the variables
 * listed in TEMPLATE_VARS. If absent, DEFAULT_TEMPLATE is used.
 */
import { promises as fs } from 'fs';
import { existsSync } from 'fs';
import path from 'path';
import { readMd, readState, roundDir } from './state.js';
import { isBlocked, parseReport } from './report.js';
import type { AssessResult, Evidence, SpearReport } from './types.js';

export interface RenderOpts {
  cwd?: string;
  templatePath?: string;
}

export interface PRContext {
  title: string;
  summary: string;
  highlights: string;
  lowlights: string;
  whatToTest: string;
  warnings: string;
  nextSteps: string;
  rounds: number;
  evidenceCount: number;
  defectsRemaining: number;
  defectsFixed: number;
  generatedAt: string;
  type: string;
  status: string;
}

export const TEMPLATE_VARS: Array<keyof PRContext> = [
  'title', 'summary', 'highlights', 'lowlights', 'whatToTest',
  'warnings', 'nextSteps', 'rounds', 'evidenceCount',
  'defectsRemaining', 'defectsFixed', 'generatedAt', 'type', 'status',
];

const DEFAULT_TEMPLATE = `# {{title}}

## Summary
{{summary}}

## Highlights
{{highlights}}

## Lowlights
{{lowlights}}

## What to test
{{whatToTest}}

## Warnings
{{warnings}}

## Next steps
{{nextSteps}}

---
*Generated by \`spear resolve\` ({{type}}, {{rounds}} round(s), {{evidenceCount}} evidence items, {{defectsRemaining}} defect(s) remaining).*
`;

/**
 * Render a PR description from the project's current state. Pure-ish: reads
 * files but does not mutate. Returns the rendered markdown.
 */
export async function renderPR(opts: RenderOpts = {}): Promise<{ markdown: string; context: PRContext }> {
  const cwd = opts.cwd ?? process.cwd();
  const state = await readState(cwd);
  if (!state) throw new Error('No SPEAR project found.');

  const scopeMd = (await readMd('scope', cwd)) ?? '';
  const resolveMd = (await readMd('resolve', cwd)) ?? '';
  const report = parseReport(resolveMd);

  const title = deriveTitle(scopeMd, state.type);
  const allReports = await collectReports(state.round, cwd);
  const allDefects = await collectDefects(state.round, cwd);
  const allEvidence = await collectEvidence(state.round, cwd);

  const ctx: PRContext = {
    title,
    summary: buildSummary(state, report, allReports.length),
    highlights: buildHighlights(allReports, state),
    lowlights: buildLowlights(allDefects, state),
    whatToTest: buildWhatToTest(allEvidence, state.type),
    warnings: buildWarnings(state, report),
    nextSteps: buildNextSteps(report, state),
    rounds: state.round,
    evidenceCount: allEvidence.length,
    defectsRemaining: state.lastAssess?.defectCount ?? 0,
    defectsFixed: state.lastAssess?.fixed ?? 0,
    generatedAt: new Date().toISOString(),
    type: state.type,
    status: deriveStatus(state, report),
  };

  const template = await loadTemplate(cwd, opts.templatePath);
  const markdown = applyTemplate(template, ctx);
  return { markdown, context: ctx };
}

function deriveTitle(scopeMd: string, type: string): string {
  const m = scopeMd.match(/##\s+Goal\s*\n([\s\S]*?)(?:\n##|\n*$)/i);
  if (m) {
    const body = m[1];
    for (const rawLine of body.split('\n')) {
      const line = rawLine.trim();
      if (!line || line.startsWith('>') || /^_.*_$/.test(line)) continue;
      const stripped = line.replace(/_[^_]*_/g, '').replace(/^[A-Z][A-Za-z\s/(),.-]*:\s*/, '').trim();
      if (stripped.length > 8) return truncate(stripped, 80);
    }
  }
  return `${type} project — close-out`;
}

function deriveStatus(state: NonNullable<Awaited<ReturnType<typeof readState>>>, report: SpearReport | null): string {
  if (state.completedAt) return 'completed (user-signaled)';
  if (state.phase === 'converged') return 'converged';
  if (isBlocked(report)) return 'blocked';
  if (state.stuckSince) return `stuck since round ${state.stuckSince}`;
  return state.phase;
}

function buildSummary(state: NonNullable<Awaited<ReturnType<typeof readState>>>, report: SpearReport | null, reportCount: number): string {
  const parts: string[] = [];
  parts.push(
    `Ran SPEAR ${state.type} pipeline through ${state.round} round(s); ` +
      `currently ${state.phase}` +
      (state.completedAt ? ` (signaled complete ${state.completedAt}).` : '.'),
  );
  const remaining = state.lastAssess?.defectCount ?? 0;
  if (remaining === 0) {
    parts.push('Convergence reached: 0 open defects.');
  } else {
    parts.push(`${remaining} open defect(s) at last assess.`);
  }
  if (reportCount === 0) {
    parts.push('No `<spear-report>` blocks recorded — highlights below are inferred from defect/evidence trail.');
  }
  if (report?.completed) parts.push(`Most recent: ${report.completed}.`);
  return parts.join(' ');
}

function buildHighlights(reports: SpearReport[], state: NonNullable<Awaited<ReturnType<typeof readState>>>): string {
  const items: string[] = [];
  // Pull COMPLETED items across reports, deduped
  const seen = new Set<string>();
  for (const r of reports) {
    if (!r.completed) continue;
    for (const piece of r.completed.split(/[,;]/).map((s) => s.trim()).filter(Boolean)) {
      const key = piece.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      items.push(`- ${piece}`);
    }
  }
  // Defect-count trend
  if (state.history && state.history.length >= 2) {
    const first = state.history[0];
    const last = state.history[state.history.length - 1];
    if (last.defectCount < first.defectCount) {
      items.push(`- Reduced defect count from ${first.defectCount} → ${last.defectCount} over ${state.history.length} round(s).`);
    }
  }
  if (state.completedAt) items.push(`- Loop closed via \`<spear-complete/>\` at ${state.completedAt}.`);
  return items.length > 0 ? items.join('\n') : '_(no highlights recorded — add `<spear-report>` blocks during the assess loop to populate)_';
}

function buildLowlights(defects: Array<{ unit: string; metric: string; severity: string; description: string }>, state: NonNullable<Awaited<ReturnType<typeof readState>>>): string {
  const items: string[] = [];
  if (defects.length === 0) {
    items.push('- No open defects.');
  } else {
    const high = defects.filter((d) => d.severity === 'high').slice(0, 5);
    const med = defects.filter((d) => d.severity === 'medium').slice(0, 5);
    for (const d of [...high, ...med]) {
      items.push(`- **${d.unit} / ${d.metric}** — ${d.description}`);
    }
    const remaining = defects.length - high.length - Math.min(med.length, 5);
    if (remaining > 0) items.push(`- _…and ${remaining} more (see \`spear assess --json\`)._`);
  }
  if (state.blockers) items.push(`- **Blocker:** ${state.blockers}`);
  return items.join('\n');
}

function buildWhatToTest(evidence: Evidence[], type: string): string {
  const items: string[] = [];
  // Group: mechanical pass, mechanical fail, subjective
  const mechFail = evidence.filter((e) => e.kind === 'mechanical' && e.pass === false);
  const subjective = evidence.filter((e) => e.kind === 'subjective');

  if (mechFail.length > 0) {
    items.push('### Mechanical checks that should now pass');
    for (const e of mechFail.slice(0, 8)) {
      items.push(`- [ ] ${e.description} (was: ${formatVal(e.actual)}, expect ${formatVal(e.expected)})`);
    }
    if (mechFail.length > 8) items.push(`- [ ] _…and ${mechFail.length - 8} more — re-run \`spear assess\` to confirm._`);
  }

  if (subjective.length > 0) {
    items.push('### Manual review');
    const verb = type === 'deck' ? 'Open and score'
      : type === 'blog' ? 'Read and rate'
      : type === 'code' ? 'Review'
      : 'Inspect';
    for (const e of subjective.slice(0, 8)) {
      const ref = e.artifact ? ` (\`${e.artifact}\`)` : '';
      items.push(`- [ ] ${verb}: ${e.description}${ref}`);
    }
    if (subjective.length > 8) items.push(`- [ ] _…and ${subjective.length - 8} more in \`evidence.json\`._`);
  }

  if (items.length === 0) items.push('- _(no evidence recorded — run `spear assess` to populate)_');
  return items.join('\n');
}

function buildWarnings(state: NonNullable<Awaited<ReturnType<typeof readState>>>, report: SpearReport | null): string {
  const items: string[] = [];
  if (state.stuckSince) {
    items.push(`- ⚠ Loop reported stuck since round ${state.stuckSince} — same defect count across rounds. Review approach before merging.`);
  }
  if (state.failureReason) {
    items.push(`- ⚠ Last execute failed: ${state.failureReason}`);
  }
  if (isBlocked(report)) {
    items.push(`- ⚠ BLOCKERS reported: ${report?.blockers}`);
  }
  if (state.round >= state.maxRounds && state.phase !== 'converged') {
    items.push(`- ⚠ Hit MAX_ROUNDS (${state.maxRounds}) without convergence.`);
  }
  if (state.completedAt && (state.lastAssess?.defectCount ?? 0) > 0) {
    items.push(
      `- ⚠ Loop signaled complete with ${state.lastAssess?.defectCount} defect(s) still open — verify these are intentional.`,
    );
  }
  return items.length > 0 ? items.join('\n') : '- None.';
}

function buildNextSteps(report: SpearReport | null, state: NonNullable<Awaited<ReturnType<typeof readState>>>): string {
  const items: string[] = [];
  if (report?.next && !/^(re-?run\s+spear\s+loop\.?|\.|n\/a)$/i.test(report.next.trim())) {
    items.push(`- ${report.next}`);
  }
  if (state.phase !== 'converged' && !state.completedAt) {
    items.push(`- Re-run \`spear loop\` to continue iterating (currently at ${state.phase}).`);
  }
  if (state.completedAt) {
    items.push('- Merge / publish the artifact.');
  }
  return items.length > 0 ? items.join('\n') : '- Ship it.';
}

async function collectReports(rounds: number, cwd: string): Promise<SpearReport[]> {
  const out: SpearReport[] = [];
  for (let i = 1; i <= rounds; i++) {
    const p = path.join(roundDir(i, cwd), 'RESOLVE.md');
    if (!existsSync(p)) continue;
    const md = await fs.readFile(p, 'utf-8');
    const r = parseReport(md);
    if (r) out.push(r);
  }
  // Also include the live RESOLVE.md (may be more recent than the last round dir's snapshot)
  const live = await readMd('resolve', cwd);
  if (live) {
    const r = parseReport(live);
    if (r) out.push(r);
  }
  return out;
}

async function collectDefects(rounds: number, cwd: string): Promise<Array<{ unit: string; metric: string; severity: string; description: string }>> {
  if (rounds === 0) return [];
  const p = path.join(roundDir(rounds, cwd), 'assess.json');
  if (!existsSync(p)) return [];
  try {
    const r = JSON.parse(await fs.readFile(p, 'utf-8')) as AssessResult;
    return r.defects;
  } catch {
    return [];
  }
}

async function collectEvidence(rounds: number, cwd: string): Promise<Evidence[]> {
  if (rounds === 0) return [];
  const p = path.join(roundDir(rounds, cwd), 'evidence.json');
  if (!existsSync(p)) return [];
  try {
    return JSON.parse(await fs.readFile(p, 'utf-8')) as Evidence[];
  } catch {
    return [];
  }
}

async function loadTemplate(cwd: string, templatePath?: string): Promise<string> {
  if (templatePath) {
    const abs = path.isAbsolute(templatePath) ? templatePath : path.join(cwd, templatePath);
    if (!existsSync(abs)) throw new Error(`Template not found: ${templatePath}`);
    return fs.readFile(abs, 'utf-8');
  }
  const local = path.join(cwd, '.spear', 'pr-template.md');
  if (existsSync(local)) return fs.readFile(local, 'utf-8');
  return DEFAULT_TEMPLATE;
}

function applyTemplate(template: string, ctx: PRContext): string {
  return template.replace(/\{\{\s*([a-zA-Z][a-zA-Z0-9_]*)\s*\}\}/g, (_, key) => {
    const v = (ctx as unknown as Record<string, unknown>)[key];
    return v === undefined || v === null ? '' : String(v);
  });
}

function formatVal(v: unknown): string {
  if (v === undefined || v === null) return 'n/a';
  if (typeof v === 'string') return v;
  return JSON.stringify(v);
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}
